[project]
name = "agent-middleware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Debarupa", email = "royc.debarupa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
agent-middleware = "agent_middleware:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
